apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: noobaa-endpoint
  labels:
    deploymentName: noobaa-endpoint
    origin: keda
    app: noobaa
    scaledobject.keda.sh/name: prometheus-scaledobject
spec:
  cooldownPeriod: 150
  pollingInterval: 30
  scaleTargetRef:
    name: noobaa-endpoint
  triggers:
    - authenticationRef: 
        name: keda-prom-creds
      metadata:
        metricName: NooBaa_num_namespace_buckets
        query: '(sum(irate(container_cpu_usage_seconds_total{pod=~"noobaa-endpoint-.*", namespace="placeholder"}[5m])) by (namespace))'
        threshold: '9000000'
      type: prometheus
